id: A8F4F7009
title: A Daily Practice of Ucchuṣma
type: translation
pechas:
- IC4A3A3CC
- I0C33A300
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:49:19.636641
  last_modified_at: 2023-01-04 11:49:19.636646
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IC4A3A3CC/7ED9: '2622'
  I0C33A300/A666: '2622'
